### ISSUE TITLE
I get an error when Schedule posts the video, it clicked on the Schedule button, but it freezes still and gives an error 

### ISSUE THREAD

**Issue by KalvinThien** [dreammis/social-auto-upload#11]
Here's the error message I received

```Traceback (most recent call last):
  File "c:\Users\KalvinThien\Downloads\social-auto-upload-main\social-auto-upload-main\examples\upload_video_to_tiktok.py", line 57, in <module>
    asyncio.run(app.main(), debug=False)
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\KalvinThien\Downloads\social-auto-upload-main\social-auto-upload-main\examples\main.py", line 234, in main
    await self.upload(playwright)
  File "c:\Users\KalvinThien\Downloads\social-auto-upload-main\social-auto-upload-main\examples\main.py", line 158, in upload
    await self.set_schedule_time(page, self.publish_date)
  File "c:\Users\KalvinThien\Downloads\social-auto-upload-main\social-auto-upload-main\examples\main.py", line 81, in set_schedule_time
    await scheduled_picker.locator('div.date-picker-input').click()
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\async_api\_generated.py", line 15706, in click
    await self._impl_obj.click(
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_locator.py", line 159, in click
    return await self._frame.click(self._selector, strict=True, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_frame.py", line 484, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 492, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.```

Thanks

**Comment by dreammis** [comment]
tiktok change its style, the repo now fixed. 
Please try it

**Comment by KalvinThien** [comment]
> tiktok change its style, the repo now fixed. Please try it

thank very much Bro

**Comment by KalvinThien** [comment]
Can you show how to get div. Exactly ? I am looking to add 1 affiliate link option, thank you

**Comment by dreammis** [comment]
I use the F12 to find the right div I want.

**Comment by KalvinThien** [comment]
I used new code, and often got this error, usually will play 1-2 videos then get this error: 

```Traceback (most recent call last):
  File "d:\tiktok_video_test_lach\full\upload_tu_dong\test\upload_video_to_tiktok.py", line 59, in <module>
    asyncio.run(app.main(), debug=False)
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "d:\tiktok_video_test_lach\full\upload_tu_dong\test\main.py", line 235, in main
    await self.upload(playwright)
  File "d:\tiktok_video_test_lach\full\upload_tu_dong\test\main.py", line 156, in upload
    await self.set_schedule_time(page, self.publish_date)
  File "d:\tiktok_video_test_lach\full\upload_tu_dong\test\main.py", line 79, in set_schedule_time
    await page.frame_locator(Tk_Locator.tk_iframe).locator('div.scheduled-container input').click()
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\async_api\_generated.py", line 15706, in click
    await self._impl_obj.click(
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_locator.py", line 159, in click
    return await self._frame.click(self._selector, strict=True, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_frame.py", line 484, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 492, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.``` 

Thanks bro

**Comment by dreammis** [comment]
maybe the element don't show immediately, I add some method to wait the element show. 
You can try it again. 
tell me again if has any problem.
