### ISSUE TITLE
视频号报错了

### ISSUE THREAD

**Issue by E2077** [dreammis/social-auto-upload#26]
PS T:\social.auto.upload> python get_tencent_cookie.py
2024-06-29 11:21:14 | SUCCESS: [+] cookie 有效
PS T:\social.auto.upload> python upload_video_to_tencent.py
2024-06-29 11:21:32 | SUCCESS: [+] cookie 有效
Traceback (most recent call last):
  File "T:\social.auto.upload\upload_video_to_tencent.py", line 22, in <module>
    title, tags = get_title_and_hashtags(str(file))
  File "T:\social.auto.upload\utils\files_times.py", line 36, in get_title_and_hashtags
    hashtags = splite_str[1].replace("#", "").split(" ")
IndexError: list index out of range

**Comment by dreammis** [comment]
如果你没有开发能力，请按照我README中的meta 文件格式来设置

**Comment by dreammis** [comment]
meta信息有误
