### ISSUE TITLE
new issue found

### ISSUE THREAD

**Issue by jbosolutions** [dreammis/social-auto-upload#30]
C:\Users\jbbag\OneDrive\Escritorio\TIK> python "C:\Users\jbbag\OneDrive\Escritorio\TIK\upload_video_to_tiktok.py"
Traceback (most recent call last):
  File "C:\Users\jbbag\OneDrive\Escritorio\TIK\upload_video_to_tiktok.py", line 17, in <module>
    cookie_setup = asyncio.run(tiktok_setup(account_file, handle=True))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbbag\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\jbbag\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbbag\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\jbbag\OneDrive\Escritorio\TIK\tk_uploader\main.py", line 42, in tiktok_setup
    if not os.path.exists(account_file) or not await cookie_auth(account_file):
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbbag\OneDrive\Escritorio\TIK\tk_uploader\main.py", line 23, in cookie_auth
    await page.wait_for_load_state('networkidle')
  File "C:\Users\jbbag\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\async_api\_generated.py", line 8753, in wait_for_load_state
    await self._impl_obj.wait_for_load_state(state=state, timeout=timeout)
  File "C:\Users\jbbag\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_page.py", line 535, in wait_for_load_state
    return await self._main_frame.wait_for_load_state(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbbag\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_frame.py", line 243, in wait_for_load_state
    return await self._wait_for_load_state_impl(state, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbbag\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_frame.py", line 271, in _wait_for_load_state_impl
    await waiter.result()
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
"commit" event fired
"domcontentloaded" event fired
"load" event fired

**Comment by dreammis** [comment]
plz check the account file
maybe you run with the example first，make the upload success, then change the param or other resources later.

**Comment by jbosolutions** [comment]
yes, I put another video, but it loads fine the first time when it makes me log in with qr.. it works fine, it uploads it, then I try to upload again.. and it gives this error

=========================== logs ===========================
"commit" event fired
"domcontentloaded" event fired
"load" event fired

**Comment by jbosolutions** [comment]
maybe is the tiktok error "You are posting too fast. Take a rest.** not sure...

**Comment by dreammis** [comment]
now, supoort thumbnail, change it to chrome.
pull the new repo
read the new README
if has any question tell me.
