### ISSUE TITLE
上传封面不行了

### ISSUE THREAD

**Issue by Buluseng** [dreammis/social-auto-upload#68]
这抖音怎么老是改动，上传封面又不行了，抖音又改了。就一个自动上传而已，这抖音怎么老是针对

**Comment by DoItEric** [comment]
#69

**Comment by DoItEric** [comment]
不是针对自动上传，
如果针对自动上传，改动绝不会这么小。并且，只有封面有问题。

**Comment by dreammis** [comment]
修复了，试一试

**Comment by XianTong-king** [comment]
Traceback (most recent call last):
  File "F:\Files\social-auto-upload-main\social-auto-upload-main\upload_video_to_douyin.py", line 30, in <module>
    asyncio.run(app.main(), debug=False)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wangxt\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\Wangxt\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Wangxt\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "F:\Files\social-auto-upload-main\social-auto-upload-main\uploader\douyin_uploader\main.py", line 237, in main
    await self.upload(playwright)
  File "F:\Files\social-auto-upload-main\social-auto-upload-main\uploader\douyin_uploader\main.py", line 171, in upload
    await self.set_thumbnail(page, self.thumbnail_path)
  File "F:\Files\social-auto-upload-main\social-auto-upload-main\uploader\douyin_uploader\main.py", line 222, in set_thumbnail
    await page.locator("div[class^='footer'] button:has-text('完成')").click()
  File "C:\Users\Wangxt\AppData\Local\Programs\Python\Python313\Lib\site-packages\playwright\async_api\_generated.py", line 15347, in click
    await self._impl_obj.click(
    ...<9 lines>...
    )
  File "C:\Users\Wangxt\AppData\Local\Programs\Python\Python313\Lib\site-packages\playwright\_impl\_locator.py", line 156, in click
    return await self._frame.click(self._selector, strict=True, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Wangxt\AppData\Local\Programs\Python\Python313\Lib\site-packages\playwright\_impl\_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\Wangxt\AppData\Local\Programs\Python\Python313\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lambda: self.inner_send(method, params, False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Wangxt\AppData\Local\Programs\Python\Python313\Lib\site-packages\playwright\_impl\_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.
Call log:
waiting for locator("div[class^='footer'] button:has-text('完成')")
作者你好，这个问题是上传封面问题吗

**Comment by Heagonx** [comment]
选择封面界面能出现，但是确认封面按钮无法点击，且显示禁止符号
D:\Tool\ChatAssistant\SocialMedia\social-auto-upload>python upload_video_to_douyin.py
[+] cookie 有效
视频文件名：D:\Tool\ChatAssistant\SocialMedia\social-auto-upload\videos\demo.mp4
标题：这位勇敢的男子为了心爱之人每天坚守 🥺❤️‍🩹
Hashtag：['坚持不懈', '爱情执着', '奋斗使者', '短视频']
2024-11-22 03:24:40 | INFO: [+]正在上传-------这位勇敢的男子为了心爱之人每天坚守 🥺❤️‍🩹.mp4
2024-11-22 03:24:40 | INFO: [-] 正在打开主页...
2024-11-22 03:24:46 | INFO:   [-] 正在填充标题和话题...
2024-11-22 03:24:47 | INFO: 总共添加4个话题
2024-11-22 03:24:47 | INFO:   [-] 正在上传视频中...
2024-11-22 03:24:49 | INFO:   [-] 正在上传视频中...
2024-11-22 03:24:51 | SUCCESS:   [-]视频上传完毕
Traceback (most recent call last):
  File "D:\Tool\ChatAssistant\SocialMedia\social-auto-upload\upload_video_to_douyin.py", line 30, in <module>
    asyncio.run(app.main(), debug=False)
  File "D:\Tool\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Tool\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Tool\Python\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Tool\ChatAssistant\SocialMedia\social-auto-upload\uploader\douyin_uploader\main.py", line 237, in main
    await self.upload(playwright)
  File "D:\Tool\ChatAssistant\SocialMedia\social-auto-upload\uploader\douyin_uploader\main.py", line 171, in upload
    await self.set_thumbnail(page, self.thumbnail_path)
  File "D:\Tool\ChatAssistant\SocialMedia\social-auto-upload\uploader\douyin_uploader\main.py", line 221, in set_thumbnail
    await finish_confirm_element.click()
  File "C:\Users\Heagonux\AppData\Roaming\Python\Python311\site-packages\playwright\async_api\_generated.py", line 15347, in click
    await self._impl_obj.click(
  File "C:\Users\Heagonux\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_locator.py", line 156, in click
    return await self._frame.click(self._selector, strict=True, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Heagonux\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\Heagonux\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Heagonux\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.
Call log:
waiting for locator("div[class^='confirmBtn']").locator("div:has-text('完成')")
  -   locator resolved to <div class="confirm-qvC4Vg">完成</div>
  - attempting click action
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #1
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #2
  -   waiting 20ms
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #3
  -   waiting 100ms
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #4
  -   waiting 100ms
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #5
  -   waiting 500ms
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #6
  -   waiting 500ms
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #7
  -   waiting 500ms
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #8
  -   waiting 500ms
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #9
  -   waiting 500ms
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #10
  -   waiting 500ms
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #11
  -   waiting 500ms
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #12
  -   waiting 500ms
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #13
  -   waiting 500ms
  -   waiting for element to be visible, enabled and stable
  -   element is not visible
  - retrying click action, attempt #14
  -   waiting 500ms
  -   waiting for element to be visible, enabled and stable
  - element was detached from the DOM, retrying

**Comment by dreammis** [comment]
粗糙修复了一下，可以试试看

**Comment by dreammis** [comment]
未见反馈，关闭了
