### ISSUE TITLE
视频号上传视频失败

### ISSUE THREAD

**Issue by zhaozhiming** [dreammis/social-auto-upload#9]
视频号上传视频失败，没有自动打开浏览器，报错信息如下：

```sh
python upload_video_to_tencent.py
[+] cookie 有效
视频文件名：/social-auto-upload/videos/demo.mp4
标题：这位勇敢的男子为了心爱之人每天坚守 🥺❤️‍🩹
Hashtag：['坚持不懈', '爱情执着', '奋斗使者', '短视频']
Traceback (most recent call last):
  File "/social-auto-upload/upload_video_to_tencent.py", line 28, in <module>
    asyncio.run(app.main(), debug=False)
  File "/miniconda3/envs/auto-upload/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/auto-upload/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/auto-upload/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/playground/social-auto-upload/tencent_uploader/main.py", line 264, in main
    await self.upload(playwright)
  File "/playground/social-auto-upload/tencent_uploader/main.py", line 134, in upload
    browser = await playwright.chromium.launch(headless=False, executable_path=self.local_executable_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/auto-upload/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 13882, in launch
    await self._impl_obj.launch(
  File "/miniconda3/envs/auto-upload/lib/python3.11/site-packages/playwright/_impl/_browser_type.py", line 94, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/auto-upload/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/auto-upload/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 513, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: BrowserType.launch: Failed to launch: Error: spawn . EACCES

Call log:
<launching> . --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/l6/btvdrkq11x1346h4ql9354th0000gn/T/playwright_chromiumdev_profile-2BdW9G --remote-debugging-pipe --no-startup-window
  - [pid=N/A] starting temporary directories cleanup
  - [pid=N/A] finished temporary directories cleanup
```

**Comment by dreammis** [comment]
https://github.com/dreammis/social-auto-upload?tab=readme-ov-file#2-%E6%8A%96%E9%9F%B3
查看关于executable_path的说明，修改后再次尝试

**Comment by zhaozhiming** [comment]
@dreammis  把executable_path改成chrome的路径就好了，多谢

**Comment by z2p** [comment]
mac的chrome路径要怎么改？

**Comment by z2p** [comment]
z2p@MacBook-Pro social-auto-upload$ python3 upload_video_to_tencent.py 
[+] cookie 有效
视频文件名：/Downloads/social-auto-upload/videos/测试1.mp4
标题：测试 🥺❤️‍🩹
Hashtag：['123', 'aaa']
Traceback (most recent call last):
  File "/Downloads/social-auto-upload/upload_video_to_tencent.py", line 28, in <module>
    asyncio.run(app.main(), debug=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Downloads/social-auto-upload/tencent_uploader/main.py", line 266, in main
    await self.upload(playwright)
  File "/Downloads/social-auto-upload/tencent_uploader/main.py", line 136, in upload
    browser = await playwright.chromium.launch(headless=False, executable_path=self.local_executable_path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 13957, in launch
    await self._impl_obj.launch(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 94, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: BrowserType.launch: Failed to launch: Error: spawn . EACCES
Call log:
<launching> . --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/w3/nwlsj82n3cl3q6yzx85p32_w0000gn/T/playwright_chromiumdev_profile-gCBzrudw1m3K --remote-debugging-pipe --no-startup-window
  - [pid=N/A] starting temporary directories cleanup
  - [pid=N/A] finished temporary directories cleanup
